pipeline {
    agent { 
        node {
            label 'docker-agent-pipeline'
            }
      }
    triggers {
        pollSCM "*/5 * * * *"
    }
    stages {
        stage('Build') {
            steps {
                echo "Building.."
                sh '''
                cd ci-cd/jenkins/sample/app
                pip install -r requirements.txt
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing.."
                sh '''
                cd ci-cd/jenkins/sample/app
                python3 hello.py
                python3 hello.py --name=Rushi
                '''
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver....'
                sh '''
                echo "doing delivery stuff.."
                '''
            }
        }
    }
}